Added unit testing for mock data
Chen3018/roger pull request #1
Opened 2024-04-01 19:56 UTC by cathyxfeiyang

2024-04-01 23:39 UTC, brycez1 requested changes
Mock tests look good. The only test that I think that would be worth adding is when the output is malformed a string of only symbol characters.

2024-04-02 00:37 UTC, brycez1 approved these changes

2024-04-02 00:37 UTC, brycez1 commented
LGTM!

2024-04-02 01:53 UTC, choksis8168 approved these changes
LGTM!

2024-04-02 03:16 UTC, merged